# Generated by Django 4.1.10 on 2023-08-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('DestinationtId', models.AutoField(primary_key=True, serialize=False)),
                ('DestinationTitle', models.CharField(max_length=500)),
                ('DestinationLocation', models.CharField(max_length=500)),
                ('DestinationDescription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationTag',
            fields=[
                ('DestinationTagId', models.AutoField(primary_key=True, serialize=False)),
                ('DestinationTagName', models.CharField(max_length=500)),
                ('DestinationtId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Activites.destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImages',
            fields=[
                ('DestinationImagetId', models.AutoField(primary_key=True, serialize=False)),
                ('DestinationImagesName', models.CharField(max_length=500)),
                ('DestinationtId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Activites.destination')),
            ],
        ),
    ]
