# Generated by Django 4.1.10 on 2023-08-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationimages',
            name='DestinationImagesName',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
