# Generated by Django 4.1.10 on 2023-08-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activites', '0002_alter_destinationimages_destinationimagesname'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='DestinationDays',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='DestinationHours',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='DestinationActivities',
            fields=[
                ('DestinationTagId', models.AutoField(primary_key=True, serialize=False)),
                ('DestinationActivities', models.CharField(max_length=500, null=True)),
                ('DestinationtId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Activites.destination')),
            ],
        ),
    ]
