# Generated by Django 4.1.10 on 2023-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activites', '0006_remove_destination_destinationdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='DestinationDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='DestinationHours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
