# Generated by Django 4.1.10 on 2023-08-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activites', '0007_destination_destinationdays_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationActivities',
            fields=[
                ('DestinationActivitiesId', models.AutoField(primary_key=True, serialize=False)),
                ('DestinationActivitiesName', models.CharField(max_length=500)),
                ('DestinationtId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Activites.destination')),
            ],
        ),
    ]
