# Generated by Django 4.1.10 on 2023-08-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activites', '0009_activity_activityttag_activityimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='DestinationDescription',
            new_name='ActivityDescription',
        ),
    ]
