# Generated by Django 4.1.10 on 2023-08-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activites', '0010_rename_destinationdescription_activity_activitydescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ActivityPrice',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='ActivityType',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
